### ISSUE TITLE
Deploy wsKLIMA

### ISSUE THREAD

**Issue by Andy2003** [KlimaDAO/klimadao-solidity#1]
Please deploy a wsKLIMA contract similar to https://github.com/OlympusDAO/olympus-contracts/blob/Version-1.1/contracts/wOHM.sol

Background:

1. The wrapped version would be better for (german) taxation, since it generates no longer any staking income
2. The wrapped version of the staked token would allow cross-chain bridging

Logic:

wsKLIMA would be a wrapped version of sKLIMA such that:
- When you wrap your sKLIMA the amount of wsKLIMA you get is: sKLIMA / index.
- 50 sKLIMA at the index of 10 gets you 5 wsKLIMA.
- Upon unwrapping wsKLIMA the amount of OHM you get is: wsKLIMA x index.
- Example: 5 wsKLIMA with an index of 12, unwraps to 60 sKLIMA
- Price of 1 wsKLIMA is always approximately = price of 1 KLIMA x Current Index

**Comment by Lostindev** [comment]
The latest votes pushed for this and it has now been implemented. 
Learn more here: https://dapp.klimadao.finance/#/wrap
