### ISSUE TITLE
[Retirement Agg] Add support for Trident pool swaps

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao-solidity#22]
Currently, paying with KLIMA to offset UBO or NBO causes the transaction to revert, since the swap step doesn't support Trident pools. 
The user has to go through the additional step of swapping KLIMA for UBO or NBO on Sushi before offsetting, which is not good user experience.

PS
I will open a corresponding frontend issue to disable KLIMA as a source for retiring UBO or NBO for now.

**Comment by cujowolf** [comment]
What amounts are they reverting? The aggregator should swap on sushi for KLIMA and then on trident for the pool tokens already.

**Comment by Atmosfearful** [comment]
@cujowolf it's an internal JSON RPC error with no helpful message. These are the params that get passed to the retireCarbon() method:

```md
0x4e78011ce80ee02d2c3e649fb657e45898257815 // KLIMA addr
0x2B3eCb0991AF0498ECE9135bcD04013d7993110c // UBO addr
BigNumber {_hex: '0x2386f26fc10000', _isBigNumber: true} // 10000000000000000 or 0.01 tonnes
true
0x20A580444DD4A90Cc8990DA7B480C5E3d605a26f // my test dev wallet
"my retirement message"
```

**Comment by ShimonD-KlimaDAO** [comment]
Might just be missing bentobox approval in both frontend and the contracts swap functions. Moved to a discord thread.
