### ISSUE TITLE
[Retirement Aggregator] BCT/USDC removed liquidity is causing failures with USDC->BCT and amountincarbon=false

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao-solidity#26]
The aggregator broke for the two cases:
1. USDC -> BCT.
2. Amountincarbon = false.

In both cases bct/usdc removed liquidity is causing an error.

It took me a while to figure this one out since my live offsetting contract broke, and Timmy also reached out to me asking for help figuring out the same error "UniswapV2Library: ZERO_ADDRESS". 

I'm opening a github issue.

The problem is with this assumption:
In RetireToucanCarbon
![image](https://user-images.githubusercontent.com/99001851/192119840-4a1bb749-b746-4555-9676-58c1c7770a78.png)

The same assumption is in the MOSS helper as well, but there's usdc/moss liquidity on quickswap so it's not an issue there

**Comment by cujowolf** [comment]
With the V1 aggregator utilizing the latest V2 interfaces, this issue should be resolved.
